### ISSUE TITLE
Aborted test script due to warnings

### ISSUE THREAD

**Issue by jonknowles** [videojs/vtt.js#48]
I've cloned the repository and installed it successfully, but when I run `npm run test` I get the following error: 

> &gt; videojs-vtt.js@0.15.2 test C:\Users\jknowles\workspace\vtt.js
> &gt; grunt
> 
> Running "jshint:files" (jshint) task
> Warning: The "path" argument must be of type string. Received type object Use --force to continue.
> 
> Aborted due to warnings.

I'm not very familiar with grunt build tools, but I've tried removing the jshint task by deleting `"jshint"` from the array on line 112 of ./Gruntfile.js. Running `npm run test` after that also fails, but it gets a bit further: 

> &gt; videojs-vtt.js@0.15.2 test C:\Users\jknowles\workspace\vtt.js
> &gt; grunt
> 
> Running "uglify:dev" (uglify) task
> File dev_build/vtt.min.js created: 56.04 kB → 21.3 kB
> 
> Running "concat:dev" (concat) task
> File dev_build/vtt.js created.
> 
> Running "mochaTest:test" (mochaTest) task
> &gt;&gt; Mocha exploded!
> &gt;&gt; TypeError: Cannot read property 'prototype' of undefined
> &gt;&gt;     at Object.<anonymous> (C:\Users\jknowles\workspace\vtt.js\node_modules\socket.io\lib\store.js:35:42)
> &gt;&gt;     at Module._compile (module.js:652:30)
> &gt;&gt;     at Object.Module._extensions..js (module.js:663:10)
> &gt;&gt;     at Module.load (module.js:565:32)
> &gt;&gt;     at tryModuleLoad (module.js:505:12)
> &gt;&gt;     at Function.Module._load (module.js:497:3)
> &gt;&gt;     at Module.require (module.js:596:17)
> &gt;&gt;     at require (internal/module.js:11:18)
> &gt;&gt;     at Object.<anonymous> (C:\Users\jknowles\workspace\vtt.js\node_modules\socket.io\lib\manager.js:15:13)
> &gt;&gt;     at Module._compile (module.js:652:30)
> Warning: Task "mochaTest:test" failed. Use --force to continue.
> 
> Aborted due to warnings.

I've tried running this on node versions 8.11.2, 10.16.3, and 13.0.1, but none of those work. Are the tests supposed to be working for this project at the moment?

**Comment by gkatsev** [comment]
Unfortunately, the test scripts are broken and can only be run on node 0.10. I've been basically testing things manually as things are changing. I hope to revamp the test suite completely soon.

**Comment by jonknowles** [comment]
Ah, that explains things. Thank you for the extremely prompt response!

**Comment by gkatsev** [comment]
You're welcome.
I'm actually in the middle of a refactor to move a bunch of things into separate files so it's a bit easier to work with this repo. Hopefully, afterwards I can start on updating tests.
